aliases:
  - &docker-parameters
    repo:
      type: string
      default: "circleci-test-cluster"
    tag:
      type: string
      default: "latest"

  - &build_environment
    working_directory: ~/data
    executor: build-executor

  - &attach_workspace
    attach_workspace:
      at: ~/data

  - &deploy_helm_chart_steps
    - checkout
    - deploy_helm_chart:
        tag: "<< parameters.tag >>"

  - &build_docker_image
    - checkout
    - bulid_and_push_docker_image_dockerhub:
        tag: "<< parameters.tag >>"

  - &prod_filters
    branches:
      only:
        - master

  - &stage_filters
    branches:
      only:
        - staging

commands:
  bulid_and_push_docker_image_dockerhub:
    description: "Bulid docker image"
    parameters: *docker-parameters
    steps:
      - docker/check
      - docker/build:
          image: "saratovsource/<< parameters.repo >>"
          tag: "<< parameters.tag >>"
      - docker/push:
          image: "saratovsource/<< parameters.repo >>"
          tag: "<< parameters.tag >>"
      - docker/build:
          image: "saratovsource/<< parameters.repo >>"
          tag: "${CIRCLE_SHA1}"
      - docker/push:
          image: "saratovsource/<< parameters.repo >>"
          tag: "${CIRCLE_SHA1}"

  bulid_and_push_docker_image_ecr:
    description: "Bulid docker image"
    parameters: *docker-parameters
    steps:
      - aws-cli/install
      - aws-cli/configure
      - aws-ecr/ecr-login
      - aws-ecr/build-image:
          repo: "<< parameters.repo >>"
          tag: "<< parameters.tag >>"
      - aws-ecr/push-image:
          repo: "<< parameters.repo >>"
          tag: "<< parameters.tag >>"
      - aws-ecr/build-image:
          repo: "<< parameters.repo >>"
          tag: "${CIRCLE_SHA1}"
      - aws-ecr/push-image:
          repo: "<< parameters.repo >>"
          tag: "${CIRCLE_SHA1}"

  deploy_helm_chart:
    description: "Deploy prepared HELM chart to server"
    parameters: *docker-parameters
    steps:
      - run:
          command: |
            mkdir ~/.kube/ && \
            echo $KUBECONFIG_BASE64 | base64 -d | xargs -0 echo > ~/.kube/config
      - helm/install-helm-client:
          version: "v2.11.0"
      - run:
          command: |
            helm upgrade app --install --set image.tag=<< parameters.tag >> --wait --timeout=60 .helm/


version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.13
  aws-ecr: circleci/aws-ecr@6.1.0
  helm: circleci/helm@0.1.2
  docker: circleci/docker@0.5.10
executors:
  build-executor:
    machine: true

workflows:
  version: 2
  master:
    jobs:
      - "Build docker image":
          name: "Build staging image"
          filters:
            <<: *stage_filters
      - "Build docker image":
          name: "Build production image"
          tag: "$(cat VERSION.txt)"
          filters:
            <<: *prod_filters
      - "Deploy helm charts":
          name: "Deploy staging chart"
          requires:
            - "Build staging image"
          filters:
            <<: *stage_filters
      - hold:
          type: approval
          name: "Approve for start production deployment"
          requires:
            - "Build production image"
          filters:
            <<: *prod_filters
      - "Deploy helm charts":
          name: "Deploy production chart"
          tag: "$(cat VERSION.txt)"
          requires:
            - "Approve for start production deployment"
          filters:
            <<: *prod_filters

jobs:
  "Build docker image":
    <<: *build_environment
    steps: *build_docker_image
    parameters: *docker-parameters
  "Deploy helm charts":
    <<: *build_environment
    steps: *deploy_helm_chart_steps
    parameters: *docker-parameters
